# Generated by Django 4.0.1 on 2022-01-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='view_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
